#!/usr/bin/env bash
#create a script that displays number from 1 to 20 

i=0
while [ "$i" -lt 20 ]; do
    # if the value is 4:bad luck 
    case "$i" in 
        4)
           echo "$i"
           echo "bad luck from China"
           ;;
        9)
            echo "$i"
            echo "bad luck from Japan"
           ;;
        17)
            echo "$i"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
        esac
        
    ((i++))
done 
